# Generated by Django 5.0.3 on 2024-03-29 08:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True)),
                ('brief', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('xref', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('vk_xref', models.URLField(blank=True, verbose_name='Ссылка ВК')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('image', models.ImageField(upload_to='sponsor_logo', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Профиль спонсора',
                'verbose_name_plural': 'Профили спонсоров',
            },
        ),
    ]
