# Generated by Django 5.0.6 on 2024-05-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_start_location'),
        ('sponsors', '0002_eventsponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, help_text='Код, который нужно указать при регистрации', max_length=64, null=True, verbose_name='Код')),
                ('referral_uuid', models.UUIDField(blank=True, help_text='Код, который используется в реферальной ссылке', null=True, verbose_name='UUID')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('expires', models.DateField(blank=True, help_text='Если не указывать - бессрочно', null=True, verbose_name='Срок действия')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event', verbose_name='Событие')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsor', verbose_name='Спонсор')),
            ],
            options={
                'verbose_name': 'Рефералка',
                'verbose_name_plural': 'Рефералки',
            },
        ),
    ]
