# Generated by Django 5.0.6 on 2024-05-28 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Код, который используется в реферальной ссылке', verbose_name='UUID'),
        ),
    ]
