# Generated by Django 5.0.6 on 2024-05-28 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_alter_referral_referral_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Код, который используется в реферальной ссылке', verbose_name='UUID'),
        ),
    ]
