# Generated by Django 5.0.3 on 2024-03-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True)),
                ('brief', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картинка')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(null=True, verbose_name='Время старта')),
                ('vk_xref', models.URLField(blank=True, verbose_name='Ссылка ВК')),
                ('finished', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True)),
                ('brief', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картинка')),
                ('distance', models.IntegerField(verbose_name='Дистанция')),
                ('map_embed_src', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на карту')),
                ('gpx', models.FileField(blank=True, upload_to='gpx', verbose_name='Трек *.gpx')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True)),
                ('brief', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Серия соревнований',
                'verbose_name_plural': 'Серии соревнований',
            },
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(blank=True, default=1, verbose_name='Приоритет')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsor', verbose_name='Спонсор')),
            ],
            options={
                'verbose_name': 'Спонсор-событие',
                'verbose_name_plural': 'Спонсор-событие',
            },
        ),
        migrations.CreateModel(
            name='EventRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(blank=True, default=1, verbose_name='Приоритет')),
                ('route_category', models.CharField(max_length=255, verbose_name='Категория')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Маршрут-событие',
                'verbose_name_plural': 'Маршрут-событие',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.series', verbose_name='Серия соревнований'),
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.series'),
        ),
    ]
