# Generated by Django 5.0.3 on 2024-03-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'Cобытия'},
        ),
        migrations.AlterModelOptions(
            name='eventroute',
            options={'verbose_name': 'Связь "Маршрут-событие"', 'verbose_name_plural': 'Связь "Маршрут-событие"'},
        ),
        migrations.AlterModelOptions(
            name='eventsponsor',
            options={'verbose_name': 'Связь "Спонсор-событие"', 'verbose_name_plural': 'Связь "Спонсор-событие"'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Mаршруты'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия соревнований', 'verbose_name_plural': 'Cерии соревнований'},
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('time', models.DurationField(blank=True, null=True, verbose_name='Время')),
                ('OTL', models.BooleanField(default=False, verbose_name='OTL (over time limit)')),
                ('DNF', models.BooleanField(default=False, verbose_name='DNF (did not finish)')),
                ('DSQ', models.BooleanField(default=False, verbose_name='DSQ (disqualified)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
