# Generated by Django 5.0.3 on 2024-03-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_user_result_user_profile_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='route',
        ),
        migrations.RemoveField(
            model_name='eventroute',
            name='route_category',
        ),
    ]
