# Generated by Django 5.0.3 on 2024-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_route_remove_eventroute_route_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('-active', '-created'), 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Mаршруты'},
        ),
        migrations.AddField(
            model_name='event',
            name='routes',
            field=models.ManyToManyField(through='events.EventRoute', to='events.route'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules_doc',
            field=models.FileField(blank=True, upload_to='event_rules', verbose_name='Регламент'),
        ),
    ]
