# Generated by Django 5.0.3 on 2024-04-04 12:39

import common.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_application_helmet_not_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Elite')], default=0, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField(verbose_name='Возраст, от')),
                ('age_max', models.IntegerField(verbose_name='Возраст, до')),
                ('gender', models.IntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=common.enums.Gender['M'])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Возрастная группа',
                'verbose_name_plural': 'Возрастные группы',
            },
        ),
    ]
