# Generated by Django 5.0.3 on 2024-04-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_application_category_agegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_info',
            field=models.CharField(default='', max_length=255, verbose_name='Номер карты'),
            preserve_default=False,
        ),
    ]
