# Generated by Django 5.0.3 on 2024-04-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_payment_info'),
        ('sponsors', '0002_eventsponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(through='sponsors.EventSponsor', to='sponsors.sponsor'),
        ),
        migrations.CreateModel(
            name='PaymentWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('active_until', models.DateField(verbose_name='Доступна до')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Интервал оплаты',
                'verbose_name_plural': 'Интервалы оплаты',
            },
        ),
    ]
