# Generated by Django 5.0.3 on 2024-04-07 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_sponsors_paymentwindow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentwindow',
            options={'ordering': ('active_until',), 'verbose_name': 'Интервал оплаты', 'verbose_name_plural': 'Интервалы оплаты'},
        ),
        migrations.AddField(
            model_name='paymentwindow',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.route', verbose_name='Маршрут'),
            preserve_default=False,
        ),
    ]
