# Generated by Django 5.0.6 on 2024-05-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_start_location'),
        ('sponsors', '0003_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsors.referral', verbose_name='Рефералка'),
        ),
    ]
