# Generated by Django 5.0.7 on 2024-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер участника'),
        ),
    ]
