# Generated by Django 5.0.7 on 2024-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Elite'), (2, 'Junior')], verbose_name='Категория'),
        ),
    ]
