# Generated by Django 5.0.7 on 2024-07-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_agegroup_number_max_agegroup_number_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='halfmarathon',
            field=models.BooleanField(default=False, verbose_name='Полумарафон'),
        ),
    ]
