# Generated by Django 5.0.7 on 2024-07-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_route_halfmarathon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='number_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер участника, до'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='number_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер участника, от'),
        ),
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
    ]
