# Generated by Django 5.0.7 on 2024-07-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_agegroup_number_max_alter_agegroup_number_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closed',
            field=models.BooleanField(default=False, verbose_name='Регистрация закрыта'),
        ),
        migrations.AlterField(
            model_name='event',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Событие закончено'),
        ),
    ]
