# Generated by Django 5.0.7 on 2024-08-06 07:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_emegrency_phone_number_event_result_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
