# Generated by Django 5.0.7 on 2024-08-06 09:40

import colorfield.fields
import common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_agegroup_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detail_template',
            field=models.CharField(default='events/detail.html', max_length=127, verbose_name='Шаблон лэндинга'),
        ),
        migrations.AddField(
            model_name='event',
            name='hx_payment_template',
            field=models.CharField(default='events/hx_payment_info.html', max_length=127, verbose_name='Шаблон платежа'),
        ),
        migrations.AddField(
            model_name='event',
            name='results_template',
            field=models.CharField(default='events/results.html', max_length=127, verbose_name='Шаблон протокола'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет фона номера'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=common.enums.Gender['M'], verbose_name='Пол'),
        ),
    ]
