# Generated by Django 5.0.7 on 2024-08-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_detail_template_event_hx_payment_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_qr',
            field=models.ImageField(blank=True, help_text='Для печати на номерах', null=True, upload_to='events/payment_qr', verbose_name='QR для оплаты'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер карты'),
        ),
    ]
