# Generated by Django 5.0.7 on 2024-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_event_payment_qr_alter_event_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL для оплаты'),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='events/payment_qr', verbose_name='QR для оплаты'),
        ),
    ]
