# Generated by Django 5.0.7 on 2024-08-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_event_payment_spb_name_event_payment_spb_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='payment_spb_name',
            new_name='payment_sbp_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='payment_spb_phone',
            new_name='payment_sbp_phone',
        ),
    ]
