# Generated by Django 5.0.7 on 2025-02-11 14:05

import common.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_rename_payment_spb_name_event_payment_sbp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bike_transfer_needed',
            field=models.BooleanField(default=False, help_text='Отметьте эту галочку, если Вас нужно довезти от города до места старта вместе с велосипедом', verbose_name='Мне потребуется трансфер с велосипедом'),
        ),
        migrations.AddField(
            model_name='application',
            name='rented_bike_needed',
            field=models.BooleanField(default=False, help_text='Отметьте эту галочку, если хотели бы участвовать на прокатном велосипеде.', verbose_name='Мне потребуется велосипед в прокат'),
        ),
        migrations.AddField(
            model_name='application',
            name='self_transfer_needed',
            field=models.BooleanField(default=False, help_text='Отметьте эту галочку, если Вас нужно довезти от города до места старта', verbose_name='Мне потребуется трансфер'),
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Elite'), (2, 'Junior'), (3, 'EliteW')], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='result',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Default'), (1, 'Elite'), (2, 'Junior'), (3, 'EliteW')], default=common.enums.Category['Default'], null=True, verbose_name='Категория'),
        ),
    ]
