# Generated by Django 5.0.7 on 2025-03-11 07:55

import common.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_application_bike_transfer_needed_and_more'),
        ('users', '0008_alter_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'Marathon'), (1, 'HeatRace')], default=common.enums.EventType['Marathon'], verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='HeatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('category', models.IntegerField(blank=True, choices=[(0, 'Default'), (1, 'Elite'), (2, 'Junior'), (3, 'EliteW')], default=common.enums.Category['Default'], null=True, verbose_name='Категория')),
                ('place', models.IntegerField(verbose_name='Место в заезде')),
                ('heat', models.CharField(blank=True, max_length=255, verbose_name='Название заезда (например, "Финал")')),
                ('time', models.DurationField(blank=True, null=True, verbose_name='Время')),
                ('status', models.IntegerField(choices=[(0, 'OK'), (1, 'OTL'), (2, 'DNF'), (3, 'DSQ')], default=common.enums.ResultStatus['OK'], verbose_name='Статус')),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.agegroup', verbose_name='Возрастная группа')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Событие')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.route', verbose_name='Маршрут')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
