# Generated by Django 5.0.7 on 2025-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_event_event_type_heatresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heatresult',
            options={'verbose_name': 'Результат [на вылет]', 'verbose_name_plural': 'Результаты [на вылет]'},
        ),
        migrations.AlterField(
            model_name='heatresult',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='heatresult',
            name='place',
            field=models.IntegerField(blank=True, verbose_name='Место в заезде'),
        ),
    ]
