# Generated by Django 5.0.7 on 2025-04-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_alter_heatresult_options_alter_heatresult_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hx_payment_template',
        ),
    ]
