# Generated by Django 5.0.7 on 2025-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_remove_event_hx_payment_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('payment_window', models.DateField(verbose_name='Действует до')),
                ('price_items', models.IntegerField(verbose_name='Цена отдельно')),
                ('price', models.IntegerField(verbose_name='Цена вместе')),
                ('events', models.ManyToManyField(to='events.event', verbose_name='События')),
            ],
        ),
    ]
