# Generated by Django 5.0.7 on 2025-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_applicationbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationbundle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
