# Generated by Django 5.0.7 on 2025-04-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_applicationbundle_description'),
        ('users', '0008_alter_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('payment_window', models.DateField(verbose_name='Действует до')),
                ('price_items', models.IntegerField(verbose_name='Цена отдельно')),
                ('price', models.IntegerField(verbose_name='Цена вместе')),
                ('events', models.ManyToManyField(to='events.event', verbose_name='События')),
            ],
            options={
                'verbose_name': 'Наборы',
                'verbose_name_plural': 'Наборы',
            },
        ),
        migrations.CreateModel(
            name='BundleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name='Оплата прошла')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.bundle', verbose_name='Набор')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Заявки на наборы',
                'verbose_name_plural': 'Заявки на наборы',
            },
        ),
        migrations.DeleteModel(
            name='ApplicationBundle',
        ),
    ]
