# Generated by Django 5.0.7 on 2025-04-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_bundle_bundleapplication_delete_applicationbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_bank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка'),
        ),
    ]
