# Generated by Django 5.0.7 on 2025-04-06 17:08

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_event_payment_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='payment_bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='payment_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='payment_sbp_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='ФИО для оплаты по СБП'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='payment_sbp_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон для оплаты по СБП'),
        ),
    ]
