# Generated by Django 5.0.7 on 2025-07-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_bundle_payment_bank_bundle_payment_info_and_more'),
        ('sponsors', '0006_sponsor_general'),
        ('users', '0008_alter_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('event', 'number'), name='unique_application_number'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('event', 'user_profile'), name='unique_application_person'),
        ),
    ]
