# Generated by Django 5.0.7 on 2026-02-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_application_unique_application_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес точки старта (для регламента)'),
        ),
    ]
