# Generated by Django 5.0.7 on 2026-02-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_event_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance_unit',
            field=models.IntegerField(choices=[(1, 'км'), (2, 'м')], default=1, verbose_name='Дистанция, размерность'),
        ),
        migrations.AddField(
            model_name='route',
            name='rules_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание (для регламента)'),
        ),
    ]
