# Generated by Django 5.0.7 on 2026-02-05 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_route_distance_unit_route_rules_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='rules_description',
        ),
        migrations.AddField(
            model_name='route',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=14400), verbose_name='Лимит времени'),
        ),
    ]
