# Generated by Django 5.1.15 on 2026-05-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_remove_route_rules_description_route_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='payment_bank',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='payment_info',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='payment_sbp_name',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='payment_sbp_phone',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_bank',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_qr',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_sbp_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_sbp_phone',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payment_url',
        ),
    ]
