# Generated by Django 5.1.15 on 2026-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_remove_bundle_payment_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_order_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alpha bank order id'),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_order_id_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Alpha bank order registration response'),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_transaction_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Alpha bank payment response'),
        ),
    ]
