# Generated by Django 5.1.15 on 2026-05-21 11:56

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_application_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_application_id',
            field=models.CharField(blank=True, default=secrets.token_hex, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_order_id_response',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_transaction_response',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
