# Generated by Django 5.1.15 on 2026-06-21 17:24
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_application_payment_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимум слотов'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_application_id',
            field=models.CharField(blank=True, default=events.models.default_payment_application_id, max_length=128, null=True),
        ),
    ]
