# Generated by Django 5.1.15 on 2026-06-21 17:26

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_event_max_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_application_id',
            field=models.CharField(blank=True, default=events.models.default_payment_application_id, max_length=16, null=True),
        ),
    ]
