# Generated by Django 5.2.15 on 2026-08-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_event_max_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='payment_application_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='payment_order_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='payment_order_id_response',
        ),
        migrations.RemoveField(
            model_name='application',
            name='payment_transaction_response',
        ),
        migrations.CreateModel(
            name='ApplicationOrder',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Alpha bank order id')),
                ('order_id_response', models.JSONField(blank=True, editable=False, null=True)),
                ('transaction_response', models.JSONField(blank=True, editable=False, null=True)),
                ('saved', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.application', verbose_name='Заявка')),
            ],
        ),
    ]
