# Generated by Django 5.2.15 on 2026-08-27 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_remove_application_payment_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
