# Generated by Django 5.2.15 on 2026-09-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_applicationorder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationorder',
            name='payment_confirmed',
            field=models.BooleanField(default=False, verbose_name='Оплата прошла'),
        ),
    ]
