# Generated by Django 5.0.3 on 2024-03-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Мужчины'), (2, 'Женщины')], default=1, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
