# Generated by Django 5.0.3 on 2024-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], verbose_name='Пол'),
        ),
    ]
