# Generated by Django 5.0.3 on 2024-03-29 18:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(help_text='Укажите точную дату рождения для определения стартовой категории', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Укажите номер телефона для связи с организаторами', max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
