# Generated by Django 5.0.3 on 2024-04-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(help_text='Укажите точную дату рождения для определениявозрастной категории на момент старта.Ваша дата рождения будет скрыта от других пользователейи не отобразится на странице результатов', verbose_name='Дата рождения'),
        ),
    ]
