# Generated by Django 5.0.3 on 2024-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(help_text='Укажите точную дату рождения для определения возрастной категории на момент старта. Ваша дата рождения будет скрыта от других пользователей и не отобразится на странице результатов ', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Откуда Вы?', max_length=255, verbose_name='Локация'),
        ),
    ]
